= Vertx 文档
Lance;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 5
:sectlinks:

== Read about

> Vert.x in Action teaches you how to build responsive, resilient, and scalable JVM applications with Vert.x using well-established reactive design patterns.

== 实例

=== vertx-hello world

vertx第一个测试实例, hello world

=== vertx-router

vertx-router路由以及子路由

=== vertx-router-restful

vertx支持restful风格url定义

```txt
    userRouter.get("/list").handler(service::list);
    userRouter.post("/info").handler(service::add);
    userRouter.put("/info").handler(service::update);
    userRouter.delete("/info/:userId").handler(service::delete);
    userRouter.get("/info/:userId").handler(service::detail);
```

=== vertx-logging

vertx配置log4j2

=== vertx-exception

vertx 异常定义, 并增加统一异常拦截处理

=== vertx-config

Vertx Config配置文件读取

=== vertx-db-mysql

mysql响应式客户端

=== vertx-db-mysql-template

mysql响应式客户端基于SqlTemplate实现

=== vertx-db-redis

Redis vertx客户端

=== vertx-mail

Mail vertx客户端

=== vertx-metrics

Metric Prometheus 客户端

=== vertx-unit

junit 5单元测试

=== vertx-mqtt

Vertx之MQTT客户端服务端发送

=== vertx-multi-verticle

Vertx之Multi Verticle共享数据

=== vertx-rabbitmq

rabbitMq消息发送

=== vertx-grpc

Vertx 集成Grpc